halt-height = 0
halt-time = 0
index-events = []
inter-block-cache = true
min-retain-blocks = 0
minimum-gas-prices = ""
pruning = "default"
pruning-interval = "0"
pruning-keep-every = "0"
pruning-keep-recent = "0"

[api]
  address = "tcp://0.0.0.0:1317"
  enable = true
  enabled-unsafe-cors = true
  max-open-connections = 1000
  rpc-max-body-bytes = 1000000
  rpc-read-timeout = 10
  rpc-write-timeout = 0
  swagger = false

[grpc]
  address = "0.0.0.0:9090"
  enable = true

[rpc]
  cors_allowed_origins = ["*"]

[state-sync]
  snapshot-interval = 0
  snapshot-keep-recent = 2

[telemetry]
  enable-hostname = false
  enable-hostname-label = false
  enable-service-label = false
  enabled = false
  global-labels = []
  prometheus-retention-time = 0
  service-name = ""
